//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace axistracking.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("axistracking.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Map.
        /// </summary>
        internal static string AbrirMapa {
            get {
                return ResourceManager.GetString("AbrirMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Not Found!.
        /// </summary>
        internal static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert in progress.
        /// </summary>
        internal static string Alerta {
            get {
                return ResourceManager.GetString("Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts without treatment.
        /// </summary>
        internal static string Alertas {
            get {
                return ResourceManager.GetString("Alertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts without treatment.
        /// </summary>
        internal static string AlertasSemTratamento {
            get {
                return ResourceManager.GetString("AlertasSemTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string Ancora {
            get {
                return ResourceManager.GetString("Ancora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancora created successfully.
        /// </summary>
        internal static string AncoraCriada {
            get {
                return ResourceManager.GetString("AncoraCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancora successfully removed.
        /// </summary>
        internal static string AncoraRemovida {
            get {
                return ResourceManager.GetString("AncoraRemovida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Ativar {
            get {
                return ResourceManager.GetString("Ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Anchor.
        /// </summary>
        internal static string AtivarAncora {
            get {
                return ResourceManager.GetString("AtivarAncora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuators.
        /// </summary>
        internal static string Atuadores {
            get {
                return ResourceManager.GetString("Atuadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update: .
        /// </summary>
        internal static string Atualizacao {
            get {
                return ResourceManager.GetString("Atualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup battery:.
        /// </summary>
        internal static string BateriaBackup {
            get {
                return ResourceManager.GetString("BateriaBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel command.
        /// </summary>
        internal static string CancelarComando {
            get {
                return ResourceManager.GetString("CancelarComando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the command?.
        /// </summary>
        internal static string CancelarComandoConfirma {
            get {
                return ResourceManager.GetString("CancelarComandoConfirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel command successfully sent..
        /// </summary>
        internal static string CancelarComandoSucesso {
            get {
                return ResourceManager.GetString("CancelarComandoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Calls.
        /// </summary>
        internal static string Chamados {
            get {
                return ResourceManager.GetString("Chamados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action.
        /// </summary>
        internal static string ChooseAction {
            get {
                return ResourceManager.GetString("ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNH to expire and expired.
        /// </summary>
        internal static string cnh {
            get {
                return ResourceManager.GetString("cnh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessed Command.
        /// </summary>
        internal static string Comando {
            get {
                return ResourceManager.GetString("Comando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Broadcast.
        /// </summary>
        internal static string ComandoAguardando {
            get {
                return ResourceManager.GetString("ComandoAguardando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures.
        /// </summary>
        internal static string ComandoFalha {
            get {
                return ResourceManager.GetString("ComandoFalha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessed Commands.
        /// </summary>
        internal static string Comandos {
            get {
                return ResourceManager.GetString("Comandos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed.
        /// </summary>
        internal static string ComandoSucesso {
            get {
                return ResourceManager.GetString("ComandoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command history.
        /// </summary>
        internal static string CommandHistory {
            get {
                return ResourceManager.GetString("CommandHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command added in queue successfully!.
        /// </summary>
        internal static string CommandSendSuccess {
            get {
                return ResourceManager.GetString("CommandSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command was placed in the submit queue. Do you want to go to a list of commands?.
        /// </summary>
        internal static string CommandSendSuccessWhereToGo {
            get {
                return ResourceManager.GetString("CommandSendSuccessWhereToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to quit?.
        /// </summary>
        internal static string ConfirmaSair {
            get {
                return ResourceManager.GetString("ConfirmaSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string CriadoPor {
            get {
                return ResourceManager.GetString("CriadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update date:.
        /// </summary>
        internal static string DataAtualizacao {
            get {
                return ResourceManager.GetString("DataAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Date.
        /// </summary>
        internal static string DataEnvio {
            get {
                return ResourceManager.GetString("DataEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date:.
        /// </summary>
        internal static string DataEvento {
            get {
                return ResourceManager.GetString("DataEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Date.
        /// </summary>
        internal static string DataFila {
            get {
                return ResourceManager.GetString("DataFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gps date:.
        /// </summary>
        internal static string DataGps {
            get {
                return ResourceManager.GetString("DataGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Processing.
        /// </summary>
        internal static string DataProcessamento {
            get {
                return ResourceManager.GetString("DataProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Desativar {
            get {
                return ResourceManager.GetString("Desativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Anchor.
        /// </summary>
        internal static string DesativarAncora {
            get {
                return ResourceManager.GetString("DesativarAncora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Details.
        /// </summary>
        internal static string detalheposicao {
            get {
                return ResourceManager.GetString("detalheposicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command details.
        /// </summary>
        internal static string DetalhesComando {
            get {
                return ResourceManager.GetString("DetalhesComando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In treatment.
        /// </summary>
        internal static string EmTratamento {
            get {
                return ResourceManager.GetString("EmTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Commands.
        /// </summary>
        internal static string EnviarComandos {
            get {
                return ResourceManager.GetString("EnviarComandos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in..
        /// </summary>
        internal static string ErroLogin {
            get {
                return ResourceManager.GetString("ErroLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the routing app.
        /// </summary>
        internal static string EscolhaAplicativo {
            get {
                return ResourceManager.GetString("EscolhaAplicativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event:.
        /// </summary>
        internal static string Evento {
            get {
                return ResourceManager.GetString("Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again. If the error persists, contact technical support .
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Map.
        /// </summary>
        internal static string FecharMapa {
            get {
                return ResourceManager.GetString("FecharMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Filter.
        /// </summary>
        internal static string FiltroEventos {
            get {
                return ResourceManager.GetString("FiltroEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps.
        /// </summary>
        internal static string GoogleMaps {
            get {
                return ResourceManager.GetString("GoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string historico {
            get {
                return ResourceManager.GetString("historico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UR History.
        /// </summary>
        internal static string HistoricoUR {
            get {
                return ResourceManager.GetString("HistoricoUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour meter.
        /// </summary>
        internal static string Horimetro {
            get {
                return ResourceManager.GetString("Horimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        internal static string Hybrid {
            get {
                return ResourceManager.GetString("Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Informacoes {
            get {
                return ResourceManager.GetString("Informacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        internal static string InformacoesAdicionais {
            get {
                return ResourceManager.GetString("InformacoesAdicionais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found, please re-login. If error persists please contact support..
        /// </summary>
        internal static string LoginNaoEncontrado {
            get {
                return ResourceManager.GetString("LoginNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password.
        /// </summary>
        internal static string LoginSenhaInvalido {
            get {
                return ResourceManager.GetString("LoginSenhaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string MapaPadrao {
            get {
                return ResourceManager.GetString("MapaPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Map.
        /// </summary>
        internal static string MapType {
            get {
                return ResourceManager.GetString("MapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in up to 30 days.
        /// </summary>
        internal static string MotoristaCnhVencer {
            get {
                return ResourceManager.GetString("MotoristaCnhVencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string MotoristaCnhVencida {
            get {
                return ResourceManager.GetString("MotoristaCnhVencida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No position details for the selected unit.
        /// </summary>
        internal static string NaoHaDetalhesPosicao {
            get {
                return ResourceManager.GetString("NaoHaDetalhesPosicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not treated.
        /// </summary>
        internal static string NaoTratados {
            get {
                return ResourceManager.GetString("NaoTratados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Commands found..
        /// </summary>
        internal static string NoCommandsFound {
            get {
                return ResourceManager.GetString("NoCommandsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer:.
        /// </summary>
        internal static string Odometro {
            get {
                return ResourceManager.GetString("Odometro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attended with occurrence.
        /// </summary>
        internal static string PontosAtendidosComOcorrencia {
            get {
                return ResourceManager.GetString("PontosAtendidosComOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attended without occurrence.
        /// </summary>
        internal static string PontosAtendidosSemOcorrencia {
            get {
                return ResourceManager.GetString("PontosAtendidosSemOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points of Service.
        /// </summary>
        internal static string PontosAtendimento {
            get {
                return ResourceManager.GetString("PontosAtendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unanswered.
        /// </summary>
        internal static string PontosNaoAtendidos {
            get {
                return ResourceManager.GetString("PontosNaoAtendidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: .
        /// </summary>
        internal static string Posicao {
            get {
                return ResourceManager.GetString("Posicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Details.
        /// </summary>
        internal static string PositionDetails {
            get {
                return ResourceManager.GetString("PositionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker(s).
        /// </summary>
        internal static string Rastreadores {
            get {
                return ResourceManager.GetString("Rastreadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated tracker(s).
        /// </summary>
        internal static string RastreadoresDesatualizados {
            get {
                return ResourceManager.GetString("RastreadoresDesatualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting.
        /// </summary>
        internal static string Roteirizacao {
            get {
                return ResourceManager.GetString("Roteirizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        internal static string Satellite {
            get {
                return ResourceManager.GetString("Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search more.
        /// </summary>
        internal static string SearchMore {
            get {
                return ResourceManager.GetString("SearchMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a command to send.
        /// </summary>
        internal static string SelectCommand {
            get {
                return ResourceManager.GetString("SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no group.
        /// </summary>
        internal static string SemGrupo {
            get {
                return ResourceManager.GetString("SemGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information.
        /// </summary>
        internal static string SemInformacao {
            get {
                return ResourceManager.GetString("SemInformacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Model.
        /// </summary>
        internal static string SemModelo {
            get {
                return ResourceManager.GetString("SemModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send command.
        /// </summary>
        internal static string SendCommand {
            get {
                return ResourceManager.GetString("SendCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        internal static string Sensores {
            get {
                return ResourceManager.GetString("Sensores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status output.
        /// </summary>
        internal static string StatusOutput {
            get {
                return ResourceManager.GetString("StatusOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay.
        /// </summary>
        internal static string Stay {
            get {
                return ResourceManager.GetString("Stay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street View.
        /// </summary>
        internal static string StreetView {
            get {
                return ResourceManager.GetString("StreetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string TelaCheia {
            get {
                return ResourceManager.GetString("TelaCheia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Screen.
        /// </summary>
        internal static string TelaNormal {
            get {
                return ResourceManager.GetString("TelaNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry.
        /// </summary>
        internal static string Telemetria {
            get {
                return ResourceManager.GetString("Telemetria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperatura {
            get {
                return ResourceManager.GetString("Temperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        internal static string Terrain {
            get {
                return ResourceManager.GetString("Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic.
        /// </summary>
        internal static string Trafego {
            get {
                return ResourceManager.GetString("Trafego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Position.
        /// </summary>
        internal static string UltimaPosicao {
            get {
                return ResourceManager.GetString("UltimaPosicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Unit.
        /// </summary>
        internal static string UnidadeRastreada {
            get {
                return ResourceManager.GetString("UnidadeRastreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units in service.
        /// </summary>
        internal static string UnidadesEmServico {
            get {
                return ResourceManager.GetString("UnidadesEmServico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked Units.
        /// </summary>
        internal static string UnidadesRastreadas {
            get {
                return ResourceManager.GetString("UnidadesRastreadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string UnidadesRastreadasAtualizadas {
            get {
                return ResourceManager.GetString("UnidadesRastreadasAtualizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated.
        /// </summary>
        internal static string UnidadesRastreadasDesatualizadas {
            get {
                return ResourceManager.GetString("UnidadesRastreadasDesatualizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially.
        /// </summary>
        internal static string UnidadesRastreadasParcialmenteAtualizadas {
            get {
                return ResourceManager.GetString("UnidadesRastreadasParcialmenteAtualizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string VeiculosDisponiveis {
            get {
                return ResourceManager.GetString("VeiculosDisponiveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string VeiculosOcupados {
            get {
                return ResourceManager.GetString("VeiculosOcupados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        internal static string Velocidade {
            get {
                return ResourceManager.GetString("Velocidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string VerDetalhes {
            get {
                return ResourceManager.GetString("VerDetalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel in progress.
        /// </summary>
        internal static string Viagens {
            get {
                return ResourceManager.GetString("Viagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        internal static string ViagensEmAndamento {
            get {
                return ResourceManager.GetString("ViagensEmAndamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string ViagensEncerradas {
            get {
                return ResourceManager.GetString("ViagensEncerradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late not started.
        /// </summary>
        internal static string ViagensNaoIniciadaAtrasadas {
            get {
                return ResourceManager.GetString("ViagensNaoIniciadaAtrasadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        internal static string ViagensNaoIniciadas {
            get {
                return ResourceManager.GetString("ViagensNaoIniciadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waze.
        /// </summary>
        internal static string Waze {
            get {
                return ResourceManager.GetString("Waze", resourceCulture);
            }
        }
    }
}
